import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  center: { justifyContent: 'center', alignItems: 'center' },
  fullCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 50,
    paddingBottom: 14,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  backButton: { width: 40, alignItems: 'flex-start' },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#111827' },
  headerSpacer: { width: 40 },
  scrollView: { flex: 1, padding: 16 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#111827', marginBottom: 10 },
  detailText: { fontSize: 14, color: '#374151', lineHeight: 20 },
  fileItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  fileInfo: { flex: 1, marginLeft: 10 },
  fileName: { fontSize: 14, color: '#1D4ED8', fontWeight: '500' },
  fileType: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  emptyAttachments: { color: '#9CA3AF', fontSize: 13 },
  acceptButton: {
    backgroundColor: '#14A800',
    marginHorizontal: 20,
    marginBottom: 20,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  acceptButtonText: { color: '#fff', fontWeight: '700' },
  errorText: { color: '#D32F2F', marginBottom: 12 },
  retryButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: { color: '#fff', fontWeight: '600' },
});
