import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    backgroundColor: '#fff',
    padding: 20,
    paddingTop: 50,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  greeting: { fontSize: 24, fontWeight: '700', color: '#111827' },
  subTitle: { marginTop: 4, color: '#6B7280' },
  statsGrid: { flexDirection: 'row', paddingHorizontal: 10, paddingTop: 12, gap: 10 },
  statCard: { flex: 1, backgroundColor: '#fff', borderRadius: 12, borderLeftWidth: 4, padding: 14 },
  statValue: { fontSize: 22, fontWeight: '700', color: '#111827', marginTop: 8 },
  statTitle: { marginTop: 4, color: '#6B7280', fontSize: 12 },
  section: { backgroundColor: '#fff', marginTop: 12, padding: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 10 },
  emptyText: { color: '#9CA3AF', fontSize: 13, paddingVertical: 4 },
  assignmentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  assignmentTitle: { fontSize: 14, fontWeight: '600', color: '#111827' },
  assignmentMeta: { marginTop: 3, fontSize: 12, color: '#6B7280' },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  actionText: { flex: 1, marginLeft: 10, fontSize: 15, color: '#111827' },
  logoutButton: {
    borderBottomWidth: 0,
    marginTop: 4,
    backgroundColor: '#FFF5F5',
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  loadingText: { color: '#666', marginTop: 8 },
});
